# Generated by Django 4.2.1 on 2023-05-03 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_aktor_genre_negara_sutradara"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        default="default_images/film.jpg",
                        null=True,
                        upload_to="film_images",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Released", "Released"), ("Upcoming", "Upcoming")],
                        default="Released",
                        max_length=15,
                    ),
                ),
                ("tahun", models.IntegerField()),
                ("deskripsi", models.TextField()),
                ("durasi", models.IntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "aktor",
                    models.ManyToManyField(
                        related_name="aktor_film", to="movie_app.aktor"
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="genre_film", to="movie_app.genre"
                    ),
                ),
                (
                    "negara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movie_app.negara",
                    ),
                ),
                (
                    "sutradara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movie_app.sutradara",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ulasan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ulasan", models.TextField()),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reviewed_film",
                        to="movie_app.film",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reviewed_made_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_create",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_create_ulasan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_update_ulasan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="ulasan",
            field=models.ManyToManyField(
                related_name="ulasan_film", to="movie_app.ulasan"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="user_create",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_create_film",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="user_update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_update_film",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ulasan",
            constraint=models.UniqueConstraint(
                fields=("user", "film"), name="nama_pengulas_film_unique"
            ),
        ),
    ]
