# Generated by Django 4.2.1 on 2023-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0003_film_ulasan_film_ulasan_film_user_create_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="negara",
        ),
        migrations.AddField(
            model_name="film",
            name="negara",
            field=models.ManyToManyField(
                related_name="negara_film", to="movie_app.negara"
            ),
        ),
    ]
