# Generated by Django 4.2.1 on 2023-05-03 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0004_remove_film_negara_film_negara"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="durasi",
            field=models.DurationField(help_text="Format: HH:MM:SS"),
        ),
        migrations.AlterField(
            model_name="film",
            name="tahun",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(9999)]
            ),
        ),
    ]
