# Generated by Django 4.2.1 on 2023-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0006_bahasa_film_bahasa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="durasi",
            field=models.PositiveIntegerField(help_text="Format: in Minutes"),
        ),
        migrations.AlterField(
            model_name="film",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="default_images/film.jpg",
                null=True,
                upload_to="film_images/",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="ulasan",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="ulasan_film", to="movie_app.ulasan"
            ),
        ),
    ]
