# Generated by Django 4.2.1 on 2023-05-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_alter_film_thumbnail_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='sutradara',
        ),
        migrations.AddField(
            model_name='film',
            name='sutradara',
            field=models.ManyToManyField(related_name='sutradara_film', to='movie_app.sutradara'),
        ),
    ]
