# Generated by Django 4.2.1 on 2023-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_remove_film_sutradara_film_sutradara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, default='film_images/film-default.jpg', null=True, upload_to='film_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=None, null=True),
        ),
    ]
