# Generated by Django 4.2.1 on 2023-07-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_alter_film_thumbnail_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, default='film_images/film-default.png', null=True, upload_to='film_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, null=True),
        ),
    ]
